### PR TITLE
add lists tab and cancer kinds

### PR DESCRIPTION
**Pull request by rkimera94**
Hi @breck7  I have raised a PR  to add the lists tab for cancer DB and a list of kinds of common cancers ready for review and suggestions!  
Screenshot 2022-11-15 at 13 13 56

### CODE REVIEW

**Comment by rkimera94** [comment]
@breck7  Or maybe can leave it open to `Common cancer types` than having `Common cancer types by CDC`. 
Though the links are pointing to CDC portal for  info

**Comment by rkimera94** [comment]
Need to check why some test is failing? but on running npm tests all is passing

**Comment by celtic-coder** [comment]
Hi Kimera (@rkimera94),

There is a fatal error on the repo having a "main" branch.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
See breck7/pldb#158

**Comment by rkimera94** [comment]
@celtic-coder    Thanks, I am trying to follow the thread on [test issue](https://github.com/breck7/pldb/issues/158). Based on the thread, could it be that I also have some hard-coded values?

**Comment by breck7** [comment]
Amazing work @rkimera94 ! Sorry about the bug. @celtic-coder solved this in PLDB but my CancerDB local copy is a messy copy/paste job. This is great motivation for me to upstream some stuff from PLDB to Jtree so we can reuse more of the same code base.

**Comment by rkimera94** [comment]
okay, thanks @breck7

**Comment by rkimera94** [comment]
@breck7  so I should expect an update or can continue to work with the code base?

**Pull request merged**
