### PR TITLE
Sample commit and part 1 of commit towards completion of Issue #23

### PR DESCRIPTION
**Pull request by ghost**
Sample commit to cancerDB.
[Sample commit and part 1 of commit towards completion of Issue](https://github.com/breck7/CancerDB/commit/f240a4e89be3c22016628316638a39970eeea98b) https://github.com/breck7/CancerDB/issues/23

### CODE REVIEW

**Comment by breck7** [comment]
Awesome @SRS-WRKS ! Is there a website for each of these? We should perhaps make that a requirement both for CancerDB and PLDB (have at least one URL).

**Comment by ghost** [comment]
Sadly no.
The most ready to use list was a list of cancer registries from africa.  
Most don't have websites. Some have email. And some have postal addresses.

**Comment by ghost** [comment]
@breck7 :websites even for cancer is mostly a western thing, i suppose :)

**Comment by breck7** [comment]
@SRS-WRKS I can't accept a pull request without links. I can't verify any of that information. All information on this site should be easy to verify from other sources.

**Comment by SRS-WRKS** [comment]
Greetings,


2 Mar 2023, 23:36 by ***@***.***:

>
>
>
>
> @SRS-WRKS <https://github.com/SRS-WRKS>>  I can't accept a pull request without links. I can't verify any of that information. 
>
>


>
>
> All information on this site should be easy to verify > e ID: > ***@***.***>
>
I am sorry. Conformational bias is debated by knowledgeable scientists.
 
 
I am just trying to earn my next paycheck.

 Says the next wikipedia contributor.

Its a joke, i am sorry.


Good day.

**Comment by ghost** [comment]
@breck7 

I will find other registries with links, I am sorry.

**Pull request closed without merging**
